import Head from "next/head";
import { useRef, useState } from "react";


export default function Home() {
  const newTodoRef = useRef("");
  const [todos, setTodos] = useState([]);


  const updateTodos = (newTodo) => {
    setTodos((previousState) => {
      return [...previousState, newTodo];
    });
  };

  function removeItem(arr, value) {
    var index = arr.indexOf(value);
    if (index > -1) {
      arr.splice(index, 1);
    }

    setTodos((previousState) => {
      return [...previousState];
    });
  }

  function deleteTodo(param) {
    removeItem(todos, param);
  }

  function deleteAllTodo() {
    setTodos(() => {
      return [];
    });
  }

  const handleKeyDown = (event) => {
    if (event.key === "Enter") {
      const newTodo = newTodoRef.current.value;
      updateTodos(newTodo);
      newTodoRef.current.value = "";
    }
  };

  return (
    <div>
      <Head>
        <title>todos{`&`}notes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/todo-icon.png" />
      </Head>

      <main>
        <section>
          <div className="container">
            <div className="text-center mt-4 mb-4 ">
              <span className="fs-4 fw-semibold text-muted">
                <span className="tcolor-brand-1 fs-2">todos</span>
                {`&`}
                <span className="tcolor-brand-2 fs-2">notes</span>
              </span>
              <br />{" "}
              <span className="fw-semibold text-muted fs-6">
                instant todos and notes
              </span>
            </div>
          </div>
        </section>
        <section className="container">
          <div className="d-flex justify-content-center">
            <div className="form__group field">
              <input
                type="input"
                className="form__field"
                placeholder="typing new todo or note"
                name="name"
                id="name"
                required
                ref={newTodoRef}
                onKeyDown={handleKeyDown}
              />
            </div>
          </div>
        </section>
        <section>
          <div className="container">
            <div className="d-flex justify-content-center">
              <div className="card border-0 bg-transparent w-50  mt-4 mb-4">
                <div className="d-flex justify-content-end">
                  {todos.length === 0 ? (
                    <div></div>
                  ) : (
                    <button
                      className="btn btn-outline-danger text-s btn-sm"
                      onClick={deleteAllTodo}
                    >
                      <span>remove all</span>
                    </button>
                  )}
                </div>
                <ul className="list-group list-group-flush mt-4">
                  {todos.map((todo, index) => (
                    <li
                      key={index}
                      className="list-group-item rounded fs-6 shadow shadow-sm py-3 bg-white"
                    >
                      <div className="row">
                        <span className="col-sm-10">
                          <span>{todo}</span>
                        </span>
                        <span className="col-sm-2">
                          <span className="d-flex justify-content-end">
                            <button
                              className="btn btn-link text-danger btn-sm"
                              onClick={() => deleteTodo(todo)}
                            >
                              <i className="bi bi-x-lg"></i>
                            </button>
                          </span>
                        </span>
                      </div>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="page-footer font-small fixed-bottom">
        <div className="footer-copyright text-center py-3 d-flex justify-content-end">
          <a
            className="text-decoration-none text-muted text-dark me-4 opacity-50"
            href="https://www.emircan.dev/"
            target="_blank"
            rel="noreferrer"
          >
            emircan.dev
          </a>
        </div>
      </footer>
    </div>
  );
}
